package net.sean.emporium.entity.animation;

import net.minecraft.client.render.entity.animation.AnimationDefinition;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class RatAnimations {
    public static final AnimationDefinition RAT_WALK = AnimationDefinition.Builder.create(0.4167f).looping().addBoneAnimation("Head",
            new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0f, AnimationHelper.createRotationalVector(0.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.0833f, AnimationHelper.createRotationalVector(-12.5f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.1667f, AnimationHelper.createRotationalVector(10.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.25f, AnimationHelper.createRotationalVector(-25.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.4167f, AnimationHelper.createRotationalVector(0.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR))).addBoneAnimation("FrontLegs",
            new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0f, AnimationHelper.createRotationalVector(-12.5f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.0833f, AnimationHelper.createRotationalVector(0.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.1667f, AnimationHelper.createRotationalVector(-25.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.25f, AnimationHelper.createRotationalVector(0.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.4167f, AnimationHelper.createRotationalVector(0.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR))).addBoneAnimation("BackLegs",
            new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0f, AnimationHelper.createRotationalVector(0.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.1667f, AnimationHelper.createRotationalVector(25.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.25f, AnimationHelper.createRotationalVector(0.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.4167f, AnimationHelper.createRotationalVector(0.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR))).addBoneAnimation("Tail",
            new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0f, AnimationHelper.createRotationalVector(-10.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.1667f, AnimationHelper.createRotationalVector(10.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.4167f, AnimationHelper.createRotationalVector(-10.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR))).addBoneAnimation("tail2",
            new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0f, AnimationHelper.createRotationalVector(22.5f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.1667f, AnimationHelper.createRotationalVector(-22.5f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.4167f, AnimationHelper.createRotationalVector(22.5f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR))).addBoneAnimation("BodyBottom",
            new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0f, AnimationHelper.createRotationalVector(0.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.0833f, AnimationHelper.createRotationalVector(-12.5f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.1667f, AnimationHelper.createRotationalVector(-7.5f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.25f, AnimationHelper.createRotationalVector(0.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.4167f, AnimationHelper.createRotationalVector(0.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR))).addBoneAnimation("Rat",
            new Transformation(Transformation.Targets.MOVE_ORIGIN,
                    new Keyframe(0.0f, AnimationHelper.createTranslationalVector(0.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.0833f, AnimationHelper.createTranslationalVector(0.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.1667f, AnimationHelper.createTranslationalVector(0.0f, 0.75f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0.0f, 0.75f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.4167f, AnimationHelper.createTranslationalVector(0.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR))).addBoneAnimation("Chest",
            new Transformation(Transformation.Targets.ROTATE,
                    new Keyframe(0.0f, AnimationHelper.createRotationalVector(0.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.0833f, AnimationHelper.createRotationalVector(12.5f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.1667f, AnimationHelper.createRotationalVector(12.5f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.25f, AnimationHelper.createRotationalVector(20.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR),
                    new Keyframe(0.4167f, AnimationHelper.createRotationalVector(0.0f, 0.0f, 0.0f),
                            Transformation.Interpolations.LINEAR))).build();
}
